from enum import StrEnum


class SourceType(StrEnum):
    GUIDELINE = "GUIDELINE"
    REFERENCE_BOOK = "REFERENCE_BOOK"
    TEXTBOOK = "TEXTBOOK"
    COURSE_MATERIAL = "COURSE_MATERIAL"
    QUESTION_BANK = "QUESTION_BANK"
    QUESTION_PAPER = "QUESTION_PAPER"
    ANSWER_KEY = "ANSWER_KEY"
    OTHER = "OTHER"


class Authority(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    ASSESSMENT = "ASSESSMENT"
    REFERENCE = "REFERENCE"
    HIGH = "HIGH"


class Status(StrEnum):
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    QUEUED = "QUEUED"
    PARSING = "PARSING"
    NORMALIZING = "NORMALIZING"
    CHUNKING = "CHUNKING"
    ENRICHING = "ENRICHING"
    EMBEDDING = "EMBEDDING"
    INDEXING = "INDEXING"
    VERIFYING_INDEX = "VERIFYING_INDEX"
    READY = "READY"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CANCELLED = "CANCELLED"
